"""Old-path import shim; module moved to annotator.rally_segmentation (Stage 2).

Import-only (no -m surface); historical ``_court_scale_boxes`` assignments in frozen scripts
are shim-local and do not propagate; dies at Stage 7.
"""
from annotator.rally_segmentation import ANKLE_L as ANKLE_L
from annotator.rally_segmentation import ANKLE_R as ANKLE_R
from annotator.rally_segmentation import WRIST_L as WRIST_L
from annotator.rally_segmentation import WRIST_R as WRIST_R
from annotator.rally_segmentation import CourtBox as CourtBox
from annotator.rally_segmentation import SERVE_START_LOOKBACK_FRAMES as SERVE_START_LOOKBACK_FRAMES
from annotator.rally_segmentation import WIDESHOT_COUNT_MED_MIN as WIDESHOT_COUNT_MED_MIN
from annotator.rally_segmentation import WIDESHOT_DRIFT_MAX as WIDESHOT_DRIFT_MAX
from annotator.rally_segmentation import ServeStartClose as ServeStartClose
from annotator.rally_segmentation import ServeStartMode as ServeStartMode
from annotator.rally_segmentation import ServeStartOptions as ServeStartOptions
from annotator.rally_segmentation import SpanOpen as SpanOpen
from annotator.rally_segmentation import WideshotInputs as WideshotInputs
from annotator.rally_segmentation import Stage8Thresholds as Stage8Thresholds
from annotator.rally_segmentation import SHIPPED_THRESHOLDS as SHIPPED_THRESHOLDS
from annotator.rally_segmentation import REST_SPEED as REST_SPEED
from annotator.rally_segmentation import REST_WINDOW as REST_WINDOW
from annotator.rally_segmentation import START_SPEED as START_SPEED
from annotator.rally_segmentation import START_MIN_FRAMES as START_MIN_FRAMES
from annotator.rally_segmentation import SMOOTH_WINDOW as SMOOTH_WINDOW
from annotator.rally_segmentation import END_REST_FRAMES as END_REST_FRAMES
from annotator.rally_segmentation import scale_thresholds as scale_thresholds
from annotator.rally_segmentation import segment_video as segment_video
from annotator.rally_segmentation import compute_speed as compute_speed
from annotator.rally_segmentation import true_runs as true_runs
from annotator.rally_segmentation import rolling_nanmedian as rolling_nanmedian
from annotator.rally_segmentation import apply_replay_mask as apply_replay_mask
from annotator.rally_segmentation import court_scale_boxes as court_scale_boxes
from annotator.rally_segmentation import court_scale_slots as court_scale_slots
from annotator.rally_segmentation import build_serve_start_dist as build_serve_start_dist
from annotator.rally_segmentation import build_serve_start_box_height as build_serve_start_box_height
from annotator.rally_segmentation import build_serve_start_wideshot_inputs as build_serve_start_wideshot_inputs
from annotator.rally_segmentation import detect_contacts as detect_contacts
from annotator.rally_segmentation import detect_contact_flags as detect_contact_flags
from annotator.rally_segmentation import suppress_contact_flags as suppress_contact_flags
from annotator.rally_segmentation import contact_proximity_ok as contact_proximity_ok
from annotator.rally_segmentation import wrist_contact_near as wrist_contact_near
from annotator.rally_segmentation import body_unit_dist_at_frame as body_unit_dist_at_frame
from annotator.rally_segmentation import span_impulses as span_impulses
from annotator.rally_segmentation import rolling_floor as rolling_floor
from annotator.rally_segmentation import impulse_cell_candidates as impulse_cell_candidates
from annotator.rally_segmentation import _rest_mask as _rest_mask
from annotator.rally_segmentation import _rolling_mean as _rolling_mean
from annotator.rally_segmentation import _find_rally_spans as _find_rally_spans
from annotator.rally_segmentation import _find_rally_spans_span_open as _find_rally_spans_span_open
from annotator.rally_segmentation import _last_rest_close as _last_rest_close
from annotator.rally_segmentation import _serve_setup_before as _serve_setup_before
from annotator.rally_segmentation import _serve_setup_before_boxheight as _serve_setup_before_boxheight
from annotator.rally_segmentation import _serve_start_find_rally_spans as _serve_start_find_rally_spans
from annotator.rally_segmentation import _wide_shot_before as _wide_shot_before
from annotator.rally_segmentation import main as main
